[package]
name = "qrcode-cli"
authors = ["Dhravya Shah"]
version = "0.5.0"
edition = "2021"
description = "A Simple CLI tool to generate QR Code"
license = "MIT"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
ureq = { version = "2.4.0"}