[package]
name = "qrcode-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
reqwest = { version = "^0.10.0", features=["blocking"] }
viuer = "0.6"